
app:
  upload:
    path: images

spring:
  servlet:
   multipart:
    max-file-size: 10000KB
    max-request-size: 10000KB

---
spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: NewdividE1
  jpa:
     properties:
       hibernate:
         format_sql: true
     show-sql: true
     hibernate.ddl-auto: update
server:
  port: 1160
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:wasinapl
    username: sa
    password: keep1234
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate.ddl-auto: update
---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: NewdividE1
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate.ddl-auto: update
---

